### ISSUE TITLE
CVAE is missed?

### ISSUE THREAD

**Issue by GillianGrayson** [Christensen-Lab-Dartmouth/MethylNet#14]
Hi! Could you please help me to find CVAE class, which you used in this line:

https://github.com/Christensen-Lab-Dartmouth/MethylNet/blob/674506b6fe346813791e424ea049bbb2431c982c/methylnet/embedding.py#L67

**Comment by jlevy44** [comment]
Hi @GillianGrayson we ended up deprecating the CVAE as the application of a convolution here may not be completely sensible in its current form. I will add a NotImplementedError here. Alternatively, feel free to check out some of the neural network structures at https://github.com/Christensen-Lab-Dartmouth/MethylCapsNet . Additionally, https://www.nature.com/articles/s42256-021-00325-y is an interesting modeling approach.

**Comment by GillianGrayson** [comment]
Thank you! I will close this issue

**Comment by jlevy44** [comment]
No problem, feel free to open if you want me to add the NotImplementedError.
