### ISSUE TITLE
Unable to run MethylNet on clean Ubuntu

### ISSUE THREAD

**Issue by rcedgar** [Christensen-Lab-Dartmouth/MethylNet#15]
I am unable to run any `MethylNet` commands. I have tried on several different computers using `conda` and `docker` without success, with a range of different errors which appear to be dependency failures of one kind or another. Following is a brief summary of an attempt on an x86_64 PC with freshly-installed Ubuntu 20.04.3 LTS (Focal Fossa).

I was not able to install `PyMethylProcess` using the `pip` method; however I was able to run the example exercises using the `docker` container.

### Error when installing via conda and pip

I installed `MethylNet` using `conda` as follows, noting changes from your instructions at https://github.com/Christensen-Lab-Dartmouth/MethylNet:

```
sudo apt install r-base-core    # R is a required dependency, pip install fails otherwise
conda create -n methylnet python=3.6
conda activate methylnet # "source activate" changed to "conda activate" for conda v4.11.0.
conda install pytorch torchvision -c pytorch
pip install methylnet
```

This install process appeared to run successfully, however running the example command line for `methylnet-embed perform_embedding` gives this error:

`ModuleNotFoundError: No module named 'networkx'`

### Error when running the docker container

Running `docker` container `joshualevy44/methylnet:0.1`, I get this error running the example command line for `methylnet-embed perform_embedding`:

```
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
```

NVIDIA driver info:

```
cat /proc/driver/nvidia/version
NVRM version: NVIDIA UNIX x86_64 Kernel Module  495.29.05  Thu Sep 30 16:00:29 UTC 2021
GCC version:  gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)

```
I realize that standard `docker` does not support CUDA, but I do not understand the notes in your installation instructions about running with or without GPUs and was not able to resolve the problem.

I've used many hours on this now and am out of ideas, help will be much appreciated.

**Comment by jlevy44** [comment]
Have you seen the docker file at https://codeocean.com/capsule/5473199/ ? Were you able to run that demo successfully? 

networkx should be installable as specified in the setup.py

Also, can you try installing the latest version of methylnet?
```
pip install git+https://github.com/Christensen-Lab-Dartmouth/MethylNet
```

For docker gpu access you may want to try nvidia-docker? https://github.com/NVIDIA/nvidia-docker

It would be helpful to post the dependency errors so I have a better idea for potential fixes if required.

**Comment by rcedgar** [comment]
I was able to install networkx using `conda install -c anaconda networkx`, now `perform_embedding` runs to completion.
